Upd
Failed to compile.

src/components/ContactList/ContactList.jsx
  Line 1:40:  'Quantitas' is defined but never used           no-unused-vars
  Line 6:10:  'RotatingLines' is defined but never used       no-unused-vars
  Line 14:9:  'isLoading' is assigned a value but never used  no-unused-vars
  Line 23:9:  'quantitas' is assigned a value but never used  no-unused-vars

Error: Process completed with exit code 1.